services:
  - type: web
    name: attendease-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    ports:
      - port: 8080
        protocol: http
        healthCheckPath: /
